name: Android Release APK Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'android/**'
      - 'react-native.config.js'
      - 'package.json'


jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'


      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build Android Release APK
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease --no-daemon

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/*.apk
